import {
  LayoutDashboard,
  Target,
  BookOpen,
  LineChart,
  Brain,
  MessageSquare,
  User,
  Users,
  Building2,
  Settings,
  Library,
  UserCircle,
  ClipboardCheck,
  CalendarClock,
  GraduationCap,
  Layers,
  BarChart3,
  ListChecks,
  ImageIcon,
  UsersRound,
  Flag,
  ClipboardList,
  Presentation,
  CalendarCheck,
  ListTodo,
  Award,
  CalendarDays,
  TrendingUp,
  Activity,
  Bell,
  UserCog,
  UserCheck,
  Gauge,
  TriangleAlert,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";

// Named registry, not a component-reference prop: a Server Component can't
// pass a component reference to a Client Component across the RSC boundary
// (AGENTS.md §7.12). Add an entry here the first time a new nav item or
// stat card needs an icon.
export const navIcons = {
  dashboard: LayoutDashboard,
  mission: Target,
  practice: BookOpen,
  progress: LineChart,
  psychology: Brain,
  interview: MessageSquare,
  student: User,
  mentees: Users,
  academy: Building2,
  settings: Settings,
  resources: Library,
  profile: UserCircle,
  evaluations: ClipboardCheck,
  sessions: CalendarClock,
  students: GraduationCap,
  batches: Layers,
  reports: BarChart3,
  ssbDay: CalendarDays,
  oir: ListChecks,
  ppdt: ImageIcon,
  gto: UsersRound,
  obstacle: Flag,
  command: ClipboardList,
  lecture: Presentation,
  conference: CalendarCheck,
  checklist: ListTodo,
  finalProgress: Award,
  performance: TrendingUp,
  activities: Activity,
  notifications: Bell,
  mentors: UserCog,
  activeStudents: UserCheck,
  readiness: Gauge,
  attention: TriangleAlert,
  access: ShieldCheck,
} satisfies Record<string, LucideIcon>;

export type NavIconName = keyof typeof navIcons;
